### ISSUE TITLE
Error while running transcribe_mic.py

### ISSUE THREAD

**Issue by neso613** [nvidia-riva/python-clients#26]
HI
I have Riva 2.7 version installed on jetson xavier nx.
I am trying to run [transcribe_mic.py](https://github.com/nvidia-riva/python-clients/blob/main/scripts/asr/transcribe_mic.py) script but failed with the below error-

`Traceback (most recent call last):
  File "transcribe_mic.py", line 75, in <module>
    main()
  File "transcribe_mic.py", line 60, in main
    with riva.client.audio_io.MicrophoneStream(
  File "/usr/local/lib/python3.8/dist-packages/riva/client/audio_io.py", line 24, in __enter__
    self._audio_stream = self._audio_interface.open(
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate
`
Please help to figure it out.
@PeganovAnton

**Comment by virajkarandikar** [comment]
Looks like Riva requested sample rate (16kHz) is not supported by your mic hardware?
Can you check if simple microphone recording at 16kHz works?

**Comment by virajkarandikar** [comment]
Closing due to inactivity. Please reopen if required.

**Comment by Muthukumar4796** [comment]
![Screenshot from 2024-09-18 19-14-51](https://github.com/user-attachments/assets/0fe77f89-6281-4e52-9efa-b3f76a4e3fae)
7 is my default i am getting this error?how to resolve it?
